name: Deploy Astro SSR to VPS

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '20'
  DEPLOY_FOLDER: '/var/www'
  CLIENT_FOLDER: '${{ env.DEPLOY_FOLDER }}/site-r312'
  SERVER_FOLDER: '${{ env.DEPLOY_FOLDER }}/server-r312'
  SERVER_ENTRY: 'entry.mjs'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Astro project
      run: npm run build

    - name: Verify build output
      run: |
        echo "Contenu du dossier dist :"
        ls -la dist/
        echo "Contenu du dossier client :"
        ls -la dist/client/
        echo "Contenu du dossier server :"
        ls -la dist/server/

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add VPS to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy client files to VPS
      run: |
        rsync -avz --delete dist/client/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ env.CLIENT_FOLDER }}/

    - name: Deploy server files to VPS
      run: |
        rsync -avz --delete dist/server/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ env.SERVER_FOLDER }}/

    - name: Install dependencies on VPS
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
          cd ${{ env.SERVER_FOLDER }} &&
          npm ci --production
        "

    - name: Stop previous server instance
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
          cd ${{ env.SERVER_FOLDER }} &&
          pm2 delete r312-app 2>/dev/null || true
        "

    - name: Start/Restart Node.js server with PM2
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
          cd ${{ env.SERVER_FOLDER }} &&
          pm2 start ${{ env.SERVER_ENTRY }} --name r312-app &&
          pm2 save
        "

    - name: Verify deployment
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
          echo 'Client files:'
          ls -la ${{ env.CLIENT_FOLDER }}/
          echo 'Server files:'
          ls -la ${{ env.SERVER_FOLDER }}/
          echo 'PM2 status:'
          pm2 status
        "