name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Installer les dépendances côté build
      - name: Install dependencies
        run: npm ci

      # 4. Compiler le projet en production
      - name: Build project
        run: npm run build

      # 5. Copier le build sur le VPS
      - name: Deploy to VPS via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22019
          source: "dist/*"
          target: "/var/www/r312/"
          strip_components: 1
          rm: false
          overwrite: true
          debug: true

      # 6. Installer toutes les dépendances côté serveur et lancer le serveur SSR
      - name: Install production dependencies on VPS and start server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22019
          script: |
            cd /var/www/r312/server
            npm install
            npm install send server-destroy kleur clsx cookie es-module-lexer
            PORT=8082 pm2 start -f entry.mjs --name r312
